# Flattener Trade Evaluation

library(plyr) 
library(zoo)
library(xts)
library(magrittr)

# Load Federal bond data from the downloaded csv
bonds = read.table(
  "https://raw.githubusercontent.com/chenbowen184/Investment-Collaborations/master/feds200628.csv", 
  header=TRUE,skip = 9, sep=",")
bonds = rename(bonds,c('X'='Dates'))

# Select only zero coupon bonds
zero_bonds = bonds[,c(1, 3,11, seq(95, 100))]
zero_bonds = zero_bonds[complete.cases(zero_bonds),]
zero_bonds$Dates <- as.Date(zero_bonds$Dates)

# Select dates between 1983-12-30 and 2017-6-30
spot_rates= xts(zero_bonds[,2:9], order.by=zero_bonds[,1])
spot_rates = spot_rates["1983-12-30::2017-06-30"]

# Rebalance the portfolio every week, use 1982-12-30 as the initial starting point
weekly_spot = spot_rates[endpoints(spot_rates, on = 'weeks',k=1)]
weekly_spot = rename(weekly_spot, c("SVENY02"="yield.2yr.on", "SVENY10"="yield.10yr.on"))

# Function that calcualte zero coupon bond prices, using continuous compounding
zero_price <- function(face_value, yield_pct, maturity){
  price = face_value*exp(-maturity*yield_pct/100)
  return (price)
}

# Add on-the-run 2yr and 10yr Bond prices
portfolio = weekly_spot[,1:2]
portfolio$price.2yr.on = zero_price(100, weekly_spot$yield.2yr.on,2)
portfolio$price.10yr.on = zero_price(100, weekly_spot$yield.10yr.on,10)

# Add DV01 for on-the-run 2-yr and 10-yr bonds
portfolio$DV01.2yr = 2*exp(-2*portfolio$yield.2yr.on/100)/100
portfolio$DV01.10yr = 10*exp(-10*portfolio$yield.10yr.on/100)/100

# Every week, longing 1 unit of 10-yr zero requires shorting x units of 2-yr zero
portfolio$X =portfolio$DV01.10yr/portfolio$DV01.2yr


# Function that calculates yield of off-the-run bonds using Nelson's model
estimated_yield <- function(Parameters, t){
  t1 = t/Parameters$TAU1
  t2 = t/Parameters$TAU2
  yield = Parameters$BETA0 + Parameters$BETA1*(1-exp(-t1))/t1 + 
    Parameters$BETA2*((1-exp(-t1))/t1 - exp(-t1)) + 
    Parameters$BETA3*((1-exp(-t2))/t2 - exp(-t2))%>%setNames("estimated yield")
  return (yield)
}

# 2 yr bond is the front leg
# Add the estimated yield for front leg
t2 = 1 + 358/365
portfolio$yield.2yr.off = estimated_yield(weekly_spot[, 3:8], t2)

# Add the estimated yield for back leg
t10 = 9 + 358/365
portfolio$yield.10yr.off = estimated_yield(weekly_spot[, 3:8], t10)

# Add the close out price (off-the-run) for 10 year bond and 2 year bond
portfolio$price.2yr.off = zero_price(100, portfolio$yield.2yr.off,t2)
portfolio$price.10yr.off = zero_price(100, portfolio$yield.10yr.off,t10)

# Find the prices difference for holding the bonds for a week
portfolio$price_difference.10yr = lag.xts(portfolio$price.10yr.off, k=-1) - portfolio$price.10yr.on
portfolio$price_difference.2yr = lag.xts(portfolio$price.2yr.off, k=-1) - portfolio$price.2yr.on

# Add interest rate earned on cash, calculates the 7-day T-bill yield as the risk free rate earned on cash
portfolio$risk_free = estimated_yield(weekly_spot[, 3:8], 7/365)

# If the capital requirement is 10%, the leverage ratio is 
leverage_ratio.10pct = 1/0.1

### spread trade function
flattener_trade <- function(portfolio, leverage_ratio){
  
  # Creating each basket of the position, the total market value of the position is
  portfolio$cost = portfolio$price.10yr.on + portfolio$X*portfolio$price.2yr.on
  
  # Create an empty vector that records the revenue by closing out the positions
  portfolio$position_revenue = c(rep(0, length(portfolio$risk_free)))
  
  # Create an empty vector that records interests earned in cash positions
  portfolio$interest_on_cash =  c(rep(0, length(portfolio$risk_free)))
  
  # Create an empty vector that records position of each week
  portfolio$position = c(rep(0, length(portfolio$risk_free)))
  
  # Create empty vector that represents the total capital each period
  portfolio$capital = c(rep(0, length(portfolio$risk_free)))
  portfolio$capital[1] = 1000000
  
  for (i in 1:(length(portfolio$capital)-1)){
    # Update position at the beginning of every week
    portfolio$position[i] = portfolio$capital[i]*leverage_ratio/portfolio$cost[i]
    num_long = portfolio$position[i]
    num_short = num_long*portfolio$X[i]
    
    # Calculate total cash on hand every week, capital last period + the left-overs for 
    # buying positions
    cash_on_hand =(portfolio$capital[i] + num_short*portfolio$price.2yr.on  
                   - num_long*portfolio$price.10yr.on)
    # Record revenue generated by closing out each position                         
    portfolio$position_revenue[i] = (num_long * portfolio$price_difference.10yr
                                     -num_short * portfolio$price_difference.2yr)
    # Record interest generated by holding the cash
    portfolio$interest_on_cash[i] = cash_on_hand*(exp(portfolio$risk_free[i]/100 *7/365))-cash_on_hand
    
    portfolio$revenue[i] = portfolio$position_revenue[i]  +portfolio$interest_on_cash[i]
    # Caculate capital next rebalancing period
    portfolio$capital[i+1] = (portfolio$capital[i]+ portfolio$position_revenue[i] 
                              +portfolio$interest_on_cash[i])
  }
  # Find the cumulative return of the flattener trading strategy, and plot the cuulative return
  total_return = portfolio
  total_return$cumulative_return = total_return$capital/1000000 - 1
  return (total_return)
}

# Question 1  - Plot the total return 
portfolio.10pct = portfolio
total_return.10pct = flattener_trade(portfolio.10pct, leverage_ratio.10pct)

plot.xts(total_return.10pct$cumulative_return,
         main = "Cumulative Return for Flattener Trading Strategy with 
         10% Capital Requirement",
         major.ticks= "years", 
         grid.ticks.on = "years",
         grid.ticks.lty = "dotted",
         col = "blue")

# Question 2 - Plot the Convexity risk over time

# For 10-year  
derivaties <-function(maturity, yield_pct)
{
  convexity=100*(-maturity)^2*exp(-maturity*yield_pct/100)
  return (convexity)
}

# Convexity risk
# 0.5*position*price*Tao*(dr)^2
# position*price=1000000
total_return.10pct$convexity_risk_10=1/2*100*(0.001)^2*1e6 - 1/2*4*(0.001)^2*total_return.10pct$X*1e6 * total_return.10pct$price.2yr.on/total_return.10pct$price.10yr.on
#total_return.10pct$convexity_risk_10=1/2*derivaties(10,weekly_spot[,2])*(0.001)^2
# Plot the convexity risk over time
plot.xts(total_return.10pct$convexity_risk_10,
         ylim = range(0,100),
         main = "Convexity Risk",
         major.ticks= "years", 
         grid.ticks.on = "years",
         grid.ticks.lty = "dotted", 
         col = "red")

# Question 3 - Spread Return, Convexity Return and Time Return

#spread return

total_return.10pct$yield_diff.10yr = lag.xts(total_return.10pct$yield.10yr.on, k = -1)-
  total_return.10pct$yield.10yr.on

total_return.10pct$yield_diff.2yr = lag.xts(total_return.10pct$yield.2yr.on, k = -1) -
  total_return.10pct$yield.2yr.on

total_return.10pct$delta_10 = -total_return.10pct$DV01.10yr*
  total_return.10pct$yield_diff.10yr

total_return.10pct$delta_2 = -total_return.10pct$DV01.2yr*
  total_return.10pct$yield_diff.2yr

total_return.10pct$spread_return= (total_return.10pct$delta_10-
                                     total_return.10pct$X*total_return.10pct$delta_2)*100*
                                    total_return.10pct$position

total_return.10pct$cum_spread_return = lag.xts((1000000 + cumsum(total_return.10pct$spread_return))/1000000 -1)

#convexity return
total_return.10pct$convexity_10=1/2*(10)^2*total_return.10pct$price.10yr.on* (total_return.10pct$yield_diff.10yr/100)^2

total_return.10pct$convexity_2=1/2*(2)^2*total_return.10pct$price.2yr.on * (total_return.10pct$yield_diff.2yr/100)^2

total_return.10pct$convexity_return= total_return.10pct$position*(total_return.10pct$convexity_10  - 
                                                                    total_return.10pct$convexity_2 * total_return.10pct$X)

total_return.10pct$cum_convexity_return = lag.xts((1000000 + cumsum(total_return.10pct$convexity_return))/1000000 - 1)

#time return

total_return.10pct$d_price_no_shift.10yr = portfolio$price.10yr.off - portfolio$price.10yr.on
total_return.10pct$d_price_no_shift.2yr = portfolio$price.2yr.off - portfolio$price.2yr.on

total_return.10pct$time_return = (total_return.10pct$d_price_no_shift.10yr - 
                                  total_return.10pct$d_price_no_shift.2yr * total_return.10pct$X)*
                                  total_return.10pct$position + total_return.10pct$interest_on_cash
total_return.10pct$cum_time_return =lag.xts((1000000+ cumsum(total_return.10pct$time_return))/1000000 - 1)

#Residual return
total_return.10pct$residual= total_return.10pct$interest_on_cash +
                            total_return.10pct$position_revenue- total_return.10pct$spread_return -
                            total_return.10pct$convexity_return- total_return.10pct$time_return

total_return.10pct$cum_residual = lag.xts((1000000 + cumsum(total_return.10pct$residual))/1000000 - 1)

# Plot the decomposed return and total return on the same plot

Returns = cbind(total_return.10pct$cumulative_return,
            total_return.10pct$cum_spread_return,
            total_return.10pct$cum_convexity_return,
            total_return.10pct$cum_time_return,
            total_return.10pct$cum_residual)

columns(Returns) <- c("cumulative total return",
                      "cumulative spread return",
                      "cumulative convexity return",
                      "cumulative time return",
                      "cumulative residual return")

plot.xts(Returns ,
         main = "Decomposed Return for Flattener Trading Strategy",
         major.ticks= "years", 
         grid.ticks.on = "years",
         grid.ticks.lty = "dotted", 
         auto.legend = TRUE,
         legend.loc = "bottomleft",
         col = rainbow(7))

# Question 4 - If the capital requirement is 2% the new leverage ratio is 50
leverage_ratio.2pct = 1/0.02
portfolio.2pct = portfolio
total_return.2pct = flattener_trade(portfolio.2pct, leverage_ratio.2pct)

plot.xts(total_return.2pct$cumulative_return,
         main = "Cumulative Return for Flattener Trading Strategy with 2% Capital Requirement",
         major.ticks= "years", 
         grid.ticks.on = "years",
         grid.ticks.lty = "dotted",
         col = "blue")
