# Flattener Trade Evaluation
# Bowen Chen, Yilan He, Su Bin Kwon, Nakul Thakare

library(plyr) 
library(zoo)
library(xts)
library(magrittr)

# Load Federal bond data from the downloaded csv
bonds = read.table(
"https://raw.githubusercontent.com/chenbowen184/Investment-Collaborations/master/feds200628.csv", 
                   header=TRUE,skip = 9, sep=",")
bonds = rename(bonds,c('X'='Dates'))

# Select only zero coupon bonds
zero_bonds = bonds[,c(1, 3,11, seq(95, 100))]
zero_bonds = zero_bonds[complete.cases(zero_bonds),]
zero_bonds$Dates <- as.Date(zero_bonds$Dates)

# Select dates between 1983-12-30 and 2017-6-30
spot_rates= xts(zero_bonds[,2:9], order.by=zero_bonds[,1])
spot_rates = spot_rates["1983-12-30::2017-06-30"]

# Rebalance the portfolio every week, use 1982-12-30 as the initial starting point
weekly_spot = spot_rates[endpoints(spot_rates, on = 'weeks',k=1)]
weekly_spot = rename(weekly_spot, c("SVENY02"="yield.2yr.on", "SVENY10"="yield.10yr.on"))

# Function that calcualte zero coupon bond prices, using continuous compounding
zero_price <- function(face_value, yield_pct, maturity){
  price = face_value*exp(-maturity*yield_pct/100)
  return (price)
}

# Add on-the-run 2yr and 10yr Bond prices
portfolio = weekly_spot[,1:2]
portfolio$price.2yr.on = zero_price(100, weekly_spot$yield.2yr.on,2)
portfolio$price.10yr.on = zero_price(100, weekly_spot$yield.10yr.on,10)

# Add DV01 for on-the-run 2-yr and 10-yr bonds
portfolio$DV01.2yr = 2*exp(-2*portfolio$yield.2yr.on/100)/10000
portfolio$DV01.10yr = 10*exp(-10*portfolio$yield.10yr.on/100)/10000

# Every week, longing 1 unit of 10-yr zero requires shorting x units of 2-yr zero
portfolio$X =portfolio$DV01.10yr/portfolio$DV01.2yr


# Function that calculates yield of off-the-run bonds using Nelson's model
estimated_yield <- function(Parameters, t){
  t1 = t/Parameters$TAU1
  t2 = t/Parameters$TAU2
  yield = Parameters$BETA0 + Parameters$BETA1*(1-exp(-t1))/t1 + 
          Parameters$BETA2*((1-exp(-t1))/t1 - exp(-t1)) + 
          Parameters$BETA3*((1-exp(-t2))/t2 - exp(-t2))%>%setNames("estimated yield")
  return (yield)
}

# 2 yr bond is the front leg
# Add the estimated yield for front leg
t2 = 1 + 358/365
portfolio$yield.2yr.off = estimated_yield(weekly_spot[, 3:8], t2)

# Add the estimated yield for back leg
t10 = 9 + 358/365
portfolio$yield.10yr.off = estimated_yield(weekly_spot[, 3:8], t10)

# Add the close out price (off-the-run) for 10 year bond and 2 year bond
portfolio$price.2yr.off = zero_price(100, portfolio$yield.2yr.off,t2)
portfolio$price.10yr.off = zero_price(100, portfolio$yield.10yr.off,t10)

# Find the prices difference for holding the bonds for a week
portfolio$price_difference.10yr = lag(portfolio$price.10yr.off, k=-1) - portfolio$price.10yr.on
portfolio$price_difference.2yr = lag(portfolio$price.2yr.off, k=-1) - portfolio$price.2yr.on

# Add interest rate earned on cash, calculates the 7-day T-bill yield as the risk free rate earned on cash
portfolio$risk_free = estimated_yield(weekly_spot[, 3:8], 7/365)

# If the capital requirement is 10%, the leverage ratio is 
leverage_ratio.10pct = 1/0.1

### spread trade function
flattener_trade <- function(portfolio, leverage_ratio){
  
  # Creating each basket of the position, it costs
  portfolio$cost = portfolio$price.10yr.on + portfolio$X*portfolio$price.2yr.on
  
  # Create an empty vector that records the revenue by closing out the positions
  portfolio$position_revenue = c(rep(0, length(portfolio$risk_free)))
  
  # Create an empty vector that records interests earned in cash positions
  portfolio$interest_on_cash =  c(rep(0, length(portfolio$risk_free)))
  
  # Create an empty vector that records position of each week
  portfolio$position = c(rep(0, length(portfolio$risk_free)))
  
  # Create empty vector that represents the total capital each period
  portfolio$capital = c(rep(0, length(portfolio$risk_free)))
  portfolio$capital[1] = 1000000
 
   for (i in 1:(length(portfolio$capital)-1)){
    # Update position at the beginning of every week
    portfolio$position[i] = portfolio$capital[i]*leverage_ratio/portfolio$cost[i]
    num_long = portfolio$position[i]
    num_short = num_long*portfolio$X[i]
   
     # Calculate total cash on hand every week, capital last period + the left-overs for 
    # buying positions
    cash_on_hand =(portfolio$capital[i] + num_short*portfolio$price.2yr.on  
                                         - num_long*portfolio$price.10yr.on)
    # Record revenue generated by closing out each position                         
    portfolio$position_revenue[i] = (num_long * portfolio$price_difference.10yr
                                     -num_short * portfolio$price_difference.2yr)
    # Record interest generated by holding the cash
    portfolio$interest_on_cash[i] = cash_on_hand*(exp(portfolio$risk_free[i]/100 *7/365))-cash_on_hand
    
    # Caculate capital next rebalancing period
     portfolio$capital[i+1] = (portfolio$capital[i]+ portfolio$position_revenue[i] 
                                +portfolio$interest_on_cash[i])
  }
  # Find the cumulative return of the flattener trading strategy, and plot the cuulative return
  total_return = portfolio
  total_return$cumulative_return = (total_return$capital/1000000 - 1)*100
  return (total_return)
}

portfolio.10pct = portfolio
total_return.10pct = flattener_trade(portfolio.10pct, leverage_ratio.10pct)

plot.xts(total_return.10pct$cumulative_return,
                main = "Cumulative Return for Flattener Trading Strategy with 10% Capital Requirement",
                major.ticks= "years", 
                grid.ticks.on = "years",
                grid.ticks.lty = "dotted",
                col = "blue")

#For 10-year  
derivaties <-function(maturity, yield_pct)
{
  convexity=100*(-maturity/100)^2*exp(-maturity*yield_pct/100)
  return (convexity)
}

# Convexity risk

total_return.10pct$convexity_risk_10=1/2*derivaties(10,weekly_spot[,2])*(0.001*0.001)

# Plot the convexity risk over time
plot.xts(total_return.10pct$convexity_risk_10,
         ylim = range(0,0.0000005),
         main = "Convexity Risk",
         major.ticks= "years", 
         grid.ticks.on = "years",
         grid.ticks.lty = "dotted", 
         col = "blue")


#spread return

total_return.10pct$yield_diff.10yr = total_return.10pct$yield.10yr.off-total_return.10pct$yield.10yr.on

total_return.10pct$yield_diff.2yr = total_return.10pct$yield.2yr.off-total_return.10pct$yield.2yr.on

total_return.10pct$delta_10 = -portfolio.10pct$DV01.10yr*portfolio.10pct$yield_diff.10yr*100
total_return.10pct$delta_2 = -portfolio.10pct$DV01.2yr*portfolio.10pct$yield_diff.2yr*100
total_return.10pct$spread_return=(portfolio.10pct$delta_10+portfolio.10pct$delta_2)*total_return.10pct$position
#total_return.10pct$cumulative_spread_return=cumsum(portfolio$spread_return)
plot.xts(portfolio$spread_return,
         main = "Spread Return",
         major.ticks= "years", 
         grid.ticks.on = "years",
         grid.ticks.lty = "dotted", 
         col = "blue")


#convexity return
total_return.10pct$convexity_risk_10=1/2*derivaties(10,weekly_spot[,2])*(portfolio.10pct$yield.10yr.off-portfolio.10pct$yield.10yr.on)^2
total_return.10pct$convexity_risk_2=1/2*derivaties(2,weekly_spot[,1])*(portfolio.10pct$yield.2yr.off-portfolio.10pct$yield.2yr.on)^2
total_return.10pct$convexity_return=((portfolio.10pct$convexity_risk_10 - portfolio.10pct$convexity_risk_2)/100)*total_return.10pct$position
#portfolio.10pct$cumulative_convexity_return=cumsum(portfolio.10pct$convexity_return)
plot.xts(portfolio.10pct$convexity_return,
         ylim = range(-0.005,0.015),
         main = "Convexity Return",
         major.ticks= "years", 
         grid.ticks.on = "years",
         grid.ticks.lty = "dotted", 
         col = "blue")

#time return
total_return.10pct$time_return_10 = portfolio.10pct$price.10yr.off -  portfolio.10pct$price.10yr.on
total_return.10pct$time_return_2 = portfolio.10pct$price.2yr.off -  portfolio.10pct$price.2yr.on
total_return.10pct$time_return = (portfolio.10pct$time_return_10 - portfolio.10pct$time_return_2 )*total_return.10pct$position
#total_return.10pct$time_return=portfolio.10pct$time_return*total_return.10pct$position
plot.xts(total_return.10pct$time_return,
         main = "Time Return",
         major.ticks= "years", 
         grid.ticks.on = "years",
         grid.ticks.lty = "dotted", 
         col = "blue")

# If the capital requirement is 2% the new leverage ratio is 200
leverage_ratio.2pct = 1/0.02
portfolio.2pct = portfolio
total_return.2pct = flattener_trade(portfolio.2pct, leverage_ratio.2pct)

plot.xts(total_return.2pct$cumulative_return,
         main = "Cumulative Return for Flattener Trading Strategy with 2% Capital Requirement",
         major.ticks= "years", 
         grid.ticks.on = "years",
         grid.ticks.lty = "dotted",
         col = "blue")
